from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

DATA_DIR = BASE_DIR / "data"
PHOTOS_DIR = DATA_DIR / "photos"
LOGS_DIR = DATA_DIR / "logs"

VIDEO_NOTE_ID = "DQACAgIAAxkBAAIBcmV4h6ugOscGJUgzLwZlz5r5RGCKAAKQOQACUsTAS9_e73rLK0n6MwQ"
GIFT_ID = "BQACAgIAAxkBAAIBrGV4x19Ap9MuU3lhu7F9ZgWVp0deAAKZPQACUsTAS_VyAVi00Zm7MwQ"
ANASTASIA_ID = "AgACAgIAAxkBAAIBq2V4x0dNpCAE7-eLLEk-rCwtFzXxAAIG1DEbUsTASwhexehjYkoVAQADAgADeAADMwQ"
AFTER_HOUR_ID = "AgACAgIAAxkBAAIBrWV4x3EDZSehRVVUmcHJGVB_wRW_AAII1DEbUsTAS-AmYAKyvtv1AQADAgADdwADMwQ"
GIFT_AFTER_REGISTER = "BQACAgIAAxkBAAICgGV5ZcqgK0szY95_lwV_VA_-7SatAAK5UwAC31jQS4IcEOWHYyo5MwQ"